project:
  name: Enterprise Data Quality Platform
  version: 0.1.0

aws:
  region: eu-central-1

snowflake:
  account: ""
  user: ""
  password: ""
  warehouse: ""
  database: ""
  schema: ""

paths:
  raw: datasets/raw
  bronze: datasets/bronze
  silver: datasets/silver
  gold: datasets/gold
  quarantine: datasets/quarantine
  metadata: metadata

validation:
  primary_key: customer_id

  rules:
    - name: Null Email
      type: "null"
      column: email

    - name: Duplicate Customer
      type: "duplicate"
      columns:
        - name
        - email

    - name: Invalid Email
      type: "email"
      column: email

    - name: Invalid Age
      type: "range"
      column: age
      minimum: 0