project:
  name: Enterprise Data Reliability Platform
  version: 1.0.0

aws:
  region: eu-central-1
  bucket: edqp

snowflake:
  account: ""
  user: ""
  password: ""
  warehouse: ""
  database: ""
  schema: ""

datasets:
  source_file: customers.csv

paths:
  raw: datasets/raw
  silver: datasets/silver
  quarantine: datasets/quarantine
  metadata: metadata

validation:
  primary_key: customer_id

  rules:
    - name: Null Email
      type: "null"
      column: email

    - name: Duplicate Customer
      type: "duplicate"
      columns:
        - name
        - email

    - name: Invalid Email
      type: "email"
      column: email

    - name: Invalid Age
      type: "range"
      column: age
      minimum: 0